brew 'coreutils'
brew 'moreutils'
brew 'findutils'
brew 'gnu-sed', args: ['default-names']
brew 'bash'
brew 'bash-completion'
brew 'wget', args: ['enable-iri']
brew 'ringojs'
brew 'narwhal'
brew 'vim', args: ['override-system-vi']
brew 'homebrew/dupes/grep'
brew 'homebrew/dupes/screen'
brew 'ag'
brew 'bfg'
brew 'foremost'
brew 'git'
brew 'hashpump'
brew 'libxml2 libxslt'
brew 'lynx'
brew 'mysql'
brew 'nmap'
brew 'p7zip'
brew 'pigz'
brew 'postgresql'
brew 'pv'
brew 'qt'
brew 'rbenv'
brew 'redis'
brew 'rename'
brew 'rhino'
brew 'ruby-build'
brew 'tre1'
brew 'ucspi-tcp'
brew 'webkit2png'
