silent! source ~/.gvimrc.local

" vim:ft=vim:

" Use the Solarized Dark theme
set background=dark
colorscheme solarized
" Use 14pt Hack - you have to install this
" https://github.com/chrissimpkins/Hack#desktop-usage
set guifont=Hack:h18
" Better line-height
set linespace=8
