" ----------
" Vim Config
" ----------
"
"
" How this works:
"
" This file is minimal.  Most of the vim settings and initialization is in
" several files in .vim/init.  This makes it easier to find things and to
" merge between branches and repos.
"
" Please do not add configuration to this file, unless it *really* needs to
" come first or last, like Vundle and sourcing the machine-local config.
" Instead, add it to one of the files in .vim/init, or create a new one.

set nocompatible               " be iMproved
filetype off                   " required!

set exrc
au BufWritePost .vimrc so $MYVIMRC " reload new vimrc whenever saved

" Based on http://erikzaadi.com/2012/03/19/auto-installing-vundle-from-your-vimrc/
let need_to_install_plugins=0
if empty(system("grep lazy_load ~/.vim/bundle/vundle/autoload/vundle.vim"))
    echo "Installing Vundle..."
    echo ""
    silent !mkdir -p ~/.vim/bundle
    silent !rm -rf ~/.vim/bundle/vundle
    silent !git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
    let need_to_install_plugins=1
endif
set rtp+=~/.vim/bundle/vundle/
call vundle#begin()

Plugin 'gmarik/vundle'

"
" Colorschemes
"
Plugin 'morhetz/gruvbox'

"
" Rails
"
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-bundler'
Plugin 'tpope/vim-endwise'

"
" General Editing
"
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-surround'
Plugin 'scrooloose/nerdcommenter'
Plugin 'godlygeek/tabular'
Plugin 'dense-analysis/ale'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'mattn/emmet-vim'

" Searching
"
Plugin 'mileszs/ack.vim'

" Give FZF access to Homebrew version
set rtp+=/usr/local/opt/fzf
Plugin 'junegunn/fzf.vim'

"
" Navigation
"
Plugin 'scrooloose/nerdtree'

"
" Languages
"
" Plugin 'neoclide/coc.nvim'
Plugin 'sheerun/vim-polyglot'

"
" Development Tool Integration
"
Plugin 'tpope/vim-fugitive' " git helpers

call vundle#end()
filetype plugin indent on

syntax on

if need_to_install_plugins == 1
  echo "Installing plugins via Vundle. Please ignore warnings afterwards."
  echo "This is a one-time operation that will take about a minute..."
  silent! PluginInstall
  echo "Done installing Vundle plugins!"
  q
endif

runtime! init/**.vim

if filereadable($HOME . "/.vimrc.local")
  source ~/.vimrc.local
endif

au BufRead,BufNewFile *.hamlc set ft=haml
au BufRead,BufNewFile *.smarty set filetype=html

" For gruvbox
autocmd vimenter * colorscheme gruvbox
