" ----------
" Vim Config
" ----------
"
"
" How this works:
"
" This file is minimal.  Most of the vim settings and initialization is in
" several files in .vim/init.  This makes it easier to find things and to
" merge between branches and repos.
"
" Please do not add configuration to this file, unless it *really* needs to
" come first or last, like Vundle and sourcing the machine-local config.
" Instead, add it to one of the files in .vim/init, or create a new one.

set nocompatible               " be iMproved
filetype off                   " required!

set exrc
au BufWritePost .vimrc so $MYVIMRC " reload new vimrc whenever saved

filetype plugin indent on

let need_to_install_plugins=0

" Install vim-plug as needed
if empty(glob('~/.vim/autoload/plug.vim'))
  echo "Installing vim-plug..."
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC

  let need_to_install_plugins=1
endif

" install plugins via vim-plug
call plug#begin('~/.vim/plugged')

" Colorschemes
"
Plug 'morhetz/gruvbox'

"
" Rails
"
Plug 'tpope/vim-rails'
Plug 'tpope/vim-bundler'
Plug 'tpope/vim-endwise'

"
" General Editing
"
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'scrooloose/nerdcommenter'
Plug 'godlygeek/tabular'
Plug 'dense-analysis/ale'
Plug 'Lokaltog/vim-easymotion'
Plug 'mattn/emmet-vim'

" Searching
"
Plug 'mileszs/ack.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

"
" Navigation
"
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }

"
" Languages
"
Plug 'neoclide/coc.nvim', { 'branch': 'release' }
Plug 'sheerun/vim-polyglot'

"
" Development Tool Integration
"
Plug 'tpope/vim-fugitive'

" Initialize plugin system
call plug#end()

syntax on

if need_to_install_plugins == 1
  echo "Installing VIM plugins. Please ignore warnings afterwards."
  echo "This is a one-time operation that will take about a minute..."
  silent! PluginInstall
  echo "Done installing VIM plugins!"
  q
endif

runtime! init/**.vim

if filereadable($HOME . "/.vimrc.local")
  source ~/.vimrc.local
endif

au BufRead,BufNewFile *.hamlc set ft=haml
au BufRead,BufNewFile *.smarty set filetype=html

" For gruvbox
autocmd vimenter * colorscheme gruvbox
