" No more backups and swap files. Use git and file writing
set nobackup
set noswapfile

" Find filetype and set indent based on filetype rules
" The plugin keyword allows you to setup some things like
" indentation by plugin
filetype plugin indent on
set nowrap
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set autoindent

syntax on

set wildignore+=*/tmp/*,*.so,*.swp,*.zip

" Ctrl-P setup, allow indexing of more things
let g:ctrlp_max_files=0
let g:ctrlp_max_depth=40

" Sane Ignore For ctrlp
let g:ctrlp_custom_ignore = {
  \ 'dir': '\v[\/](\.git|node_modules|vendor|third_party)$',
  \ 'file': '\.log$\',
  \ }

" Highlight matching parenthesis etc
set showmatch

" Highlight found words from search and as you type
set hlsearch
set incsearch

" Allow search to be ended by pressing Escape
nnoremap <silent> <Esc> :nohlsearch<Bar>:echo<CR>

" Hide buffer rather than closing it.
" This will retain undo and marks in the buffer
set hidden

" Keeps more history of commands etc
set history=100

" Show line numbers in left gutter
set number

" Show a colour at column 90
set colorcolumn=90

" Reload .vimrc by leader + s
map <leader>s :source ~/.vimrc<CR>

" Automatically remove excess white spaces on save
autocmd BufWritePre * :%s/\s\+$//e

" Plugins with vim-plug (https://github.com/junegunn/vim-plug)
" vim-plug should've been install by the boostrap.sh script
call plug#begin('~/.vim/plugged')
  Plug 'altercation/vim-colors-solarized'

  " Ctrl-P searching
  Plug 'kien/ctrlp.vim'

  " Quickly comment blocks etc
  Plug 'scrooloose/nerdcommenter'

  " Navigation
  Plug 'scrooloose/nerdcommenter'

  " Nicer status bar
  Plug 'itchyny/lightline.vim'

  " Tab autocompletion
  Plug 'ervandew/supertab'

  " Helpful Git stuff like :Gblame
  Plug 'tpope/vim-fugitive'

  " Multiple cursor feature
  Plug 'terryma/vim-multiple-cursors'

  " Rails and Ruby specific stuff
  Plug 'tpope/vim-rails'
  "Plug 'tpope/vim-ruby' this doesnt' currently install
  Plug 'tpope/vim-bundler'
  Plug 'tpope/vim-endwise'
call plug#end()

" Solarized colourscheme with dark background
set background=dark
colorscheme solarized

